### ISSUE TITLE
Cannot run CLI with ts-node

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#233]
Running CLI with ts-node results in an error when executing any AskScript code: `Cannot find module './parser/askscript.grammar'`

ts-node + CLI is useful for speeding up debugging and implementing new features & resources.

```
Lukaszs-MacBook-Pro:askql milimetr$ ts-node --files src/cli.ts 
🦄 3
Uncaught Error: Cannot find module './parser/askscript.grammar'
Require stack:
- /Users/milimetr/Desktop/x/askql/src/askscript/index.ts
- /Users/milimetr/Desktop/x/askql/src/cli.ts
    at Generator.next (<anonymous>)
    at REPLServer.<anonymous> (/Users/milimetr/Desktop/x/askql/src/cli.ts:58:38)
    at Object.parse (/Users/milimetr/Desktop/x/askql/src/askscript/index.ts:60:27)
    at parseToAst (/Users/milimetr/Desktop/x/askql/src/askscript/index.ts:26:23)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/milimetr/Desktop/x/askql/src/askscript/index.ts',
    '/Users/milimetr/Desktop/x/askql/src/cli.ts'
  ]
}
🦄 
```

**Comment by mhagmajer** [comment]
That would be awesome! We would need `ts-node` to take care of compiling AskScript parser or just do this https://github.com/xFAANG/askql/issues/60

**Comment by mhagmajer** [comment]
What's your plan on this @czerwinskilukasz1 ?

**Comment by czerwinskilukasz1** [comment]
It seems as a workaround one can run:
```
npx pegjs src/askscript/parser/askscript.grammar.pegjs && ts-node --files src/cli.ts
```

Which is enough for now. Removing v1.2 tag.

**Comment by czerwinskilukasz1** [comment]
Fixed with `npm run cli:dev` command.
