### ISSUE TITLE
while fails when iterating many times

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#243]
`while` works fine when it iterates a couple of times but at some number of iterations it fails. In the example below the number of iterations were between 64 and 65 000 times:

```
🦄 .editor 
// Entering editor mode (^D to finish, ^C to cancel)
let a = 1
while(a>0) {
  if ((a/1000):equals(floor(a/1000))) {
    log(a)
  }
  a=a+1
}


1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
...
62000
63000
64000
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at AsyncHook.init (domain.js:68:15)
    at PromiseWrap.emitInitNative (internal/async_hooks.js:127:43)
    at Promise.then (<anonymous>)
    at step (/Users/milimetr/Desktop/x/askql/dist/utils/index.js:7:91)
    at /Users/milimetr/Desktop/x/askql/dist/utils/index.js:8:9
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/x/askql/dist/utils/index.js:4:12)
    at Object.asyncMap (/Users/milimetr/Desktop/x/askql/dist/utils/index.js:76:12)
    at Resource.<anonymous> (/Users/milimetr/Desktop/x/askql/dist/askvm/resources/core/call.js:29:45)
```

Run using commit f527c5c (master, the latest commit)

**Comment by czerwinskilukasz1** [comment]
Actually, when my program was:
```
let c = 1
let a = 1
while(a>0) {
  if (c >= 1) {
    if ((a/1000):equals(floor(a/1000))) {
      log(a)
    }
  }
  a=a+1
}
```
it took only 53 000 iterations to fail:

```
...
52000
53000
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at AsyncHook.init (domain.js:68:15)
    at PromiseWrap.emitInitNative (internal/async_hooks.js:127:43)
    at Promise.then (<anonymous>)
    at step (/Users/milimetr/Desktop/askql/askql/dist/utils/index.js:7:91)
    at /Users/milimetr/Desktop/askql/askql/dist/utils/index.js:8:9
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/askql/askql/dist/utils/index.js:4:12)
    at Object.asyncMap (/Users/milimetr/Desktop/askql/askql/dist/utils/index.js:76:12)
    at Resource.<anonymous> (/Users/milimetr/Desktop/askql/askql/dist/askvm/lib/resource.js:53:48)
Lukaszs-MacBook-Pro:askql milimetr$ npm run build && node dist/cli.js
```

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 thank you Łukasz for testing it so well!

**Comment by czerwinskilukasz1** [comment]
👍
