### ISSUE TITLE
Inconsistent behavior when handling too many/too few function arguments.

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#267]
While Ask silently permits passing too many arguments to a function, it fails in runtime when passing too few.

```
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
const f = fun(a) { a+1 }
f(2,3)

int ask(const('f',fun(let('a',get('$0')),call(get('+'),get('a'),1))),call(get('f'),2,3))
3
```

```
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
const f = fun(a) { a+1 }
f()

Uncaught Error: Unknown identifier '$0'!
    at Object.<anonymous> (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:70:15)
    at Generator.next (<anonymous>)
    at /Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:4:12)
    at Object.run (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:29:12)
🦄 
```

Expected: either an error in both cases or a success in both cases.

**Comment by mhagmajer** [comment]
JavaScript is exactly the same. What would you suggest here @czerwinskilukasz1?

**Comment by czerwinskilukasz1** [comment]
> JavaScript is exactly the same. 

And I think this is not a good behavior.
I suggest throwing an error in both cases.

**Comment by mhagmajer** [comment]
These days ECMAScript has a pretty good around it to introduce new versions of the standard. Let's be very thorough when analysing if we should be less flexible than new JavaScripts. It would be make debugging easier if Ask programming environment offered good helpful errors.

Some functions takes variable number of arguments - for example `call`. To allow checking number of arguments, we would need to figure out how a programmer can say how many arguments their functions expects, for example:

```
fun (a, ...rest, z) {
   // rest is an array, possibly empty
}
```

Maybe there are other ways, let's explore.
