### ISSUE TITLE
CLI fails with error when trying to run AskCode 

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#268]
Following [@mhagmajer's comment](https://github.com/xFAANG/askql/issues/224#issuecomment-649785321), CLI is supposed to fully support AskCode programs.
I paste below an example which currently does not work.

AskScript (works):
```
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
find(philosophers, fun(name) { scorePerPhilosopher:at(name):is(max(scorePerPhilosopher)) })

string ask(call(get('find'),get('philosophers'),fun(let('name',get('$0')),call(get('is'),call(get('at'),get('scorePerPhilosopher'),get('name')),call(get('max'),get('scorePerPhilosopher'))))))
'Turing'
```

Now let's try running the AskCode which CLI produced for this AskScript program:
```
🦄 ask(call(get('find'),get('philosophers'),fun(let('name',get('$0')),call(get('is'),call(get('at'),get('scorePerPhilosopher'),get('name')),call(get('max'),get('scorePerPhilosopher'))))))
Uncaught Error: Unknown identifier '$0'!
    at Object.<anonymous> (/Users/milimetr/Desktop/askql/askql/dist/askvm/lib/run.js:70:15)
    at Generator.next (<anonymous>)
    at /Users/milimetr/Desktop/askql/askql/dist/askvm/lib/run.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/askql/askql/dist/askvm/lib/run.js:4:12)
    at Object.run (/Users/milimetr/Desktop/askql/askql/dist/askvm/lib/run.js:29:12)
🦄 
```
and it fails with an error.

**Comment by mhagmajer** [comment]
Confirmed

```
🦄 find(philosophers, fun { scorePerPhilosopher[$0]:is(max(scorePerPhilosopher)) })
string ask(call(get('find'),get('philosophers'),fun(call(get('is'),call(get('at'),get('scorePerPhilosopher'),get('$0')),call(get('max'),get('scorePerPhilosopher'))))))
'Turing'
🦄 ask(call(get('find'),get('philosophers'),fun(call(get('is'),call(get('at'),get('scorePerPhilosopher'),get('$0')),call(get('max'),get('scorePerPhilosopher'))))))
Uncaught Error: Unknown identifier '$0'!
    at Object.<anonymous> (/Users/marcin/Repositories/askql/dist/askvm/lib/run.js:69:15)
    at Generator.next (<anonymous>)
    at /Users/marcin/Repositories/askql/dist/askvm/lib/run.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/marcin/Repositories/askql/dist/askvm/lib/run.js:4:12)
    at Object.run (/Users/marcin/Repositories/askql/dist/askvm/lib/run.js:28:12)
```
