### ISSUE TITLE
AskScript: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by Tuhaj** [xFAANG/askql#68]
Watching https://youtu.be/Su1FBJ5r7CU?t=221 shows running the current snippet
should be possible:

`find(philosophers, fun(is(at(scorePerPhilosopher, get('$0')), max(scorePerPhilosopher))))`

However, here is what happens:

```
🦄 find(philosophers, fun(is(at(scorePerPhilosopher, get('$0')), max(scorePerPhilosopher))))
Thrown:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Resource.<anonymous> (/Users/piotrzientara/xfaang/askql/dist/askvm/resources/core/get.js:19:29)
    at Generator.next (<anonymous>)
    at /Users/piotrzientara/xfaang/askql/dist/askvm/resources/core/get.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/piotrzientara/xfaang/askql/dist/askvm/resources/core/get.js:4:12)
    at Resource.compute (/Users/piotrzientara/xfaang/askql/dist/askvm/resources/core/get.js:18:16)
    at Object.<anonymous> (/Users/piotrzientara/xfaang/askql/dist/askvm/lib/run.js:37:56)
    at Generator.next (<anonymous>)
```

**Comment by mhagmajer** [comment]
Related to #46

**Comment by mhagmajer** [comment]
@Tuhaj  The outstanding issues regarding `call` have been fixed. I assume your code is in AskScript not AskCode, in this case the valid code for what you're doing is:

```ask
ask {
  find(philosophers, fun(name) { scorePerPhilosopher:at(name):is(max(scorePerPhilosopher)) })
}
```

And it produces the expected answer:

```
🦄 find(philosophers, fun(name) { scorePerPhilosopher:at(name):is(max(scorePerPhilosopher)) })
string ask(call(get('find'),get('philosophers'),fun(let('name',get('$0')),call(get('is'),call(get('at'),get('scorePerPhilosopher'),get('name')),call(get('max'),get('scorePerPhilosopher'))))))
'Turing'
```
