### ISSUE TITLE
Can't define a variable in for

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#72]
The following code results in an error:

```
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
for(let i = 0; i < 5; i = i + 1) {
    
  }
  
Uncaught Error: Unknown identifier 'i'!
    at Object.<anonymous> (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:47:15)
    at Generator.next (<anonymous>)
    at /Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:4:12)
    at Object.run (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:22:12)
```

**Comment by czerwinskilukasz1** [comment]
Seems fixed with https://github.com/xFAANG/askql/pull/212

**Comment by mhagmajer** [comment]
Right, thanks for noticing!
